change default qos to volatile and best effort
foxglove/ros2 pull request #156
Opened 2022-03-20 11:42 UTC by wep21

**Public-Facing Changes**

"None"

**Description**

change default qos(reliability: reliable->best_effrot, durability: transient_local->volatile)
because best effort and volatile are always compatible with any publisher qos.
https://docs.ros.org/en/rolling/Concepts/About-Quality-of-Service-Settings.html
I confirmed the default qos is changed when testing with `yarn examples:listener`.
```
❯ yarn examples:listener
❯ ros2 run demo_nodes_cpp talker
❯ ros2 topic info -v /chatter
Type: std_msgs/msg/String

Publisher count: 1

Node name: talker
Node namespace: /
Topic type: std_msgs/msg/String
Endpoint type: PUBLISHER
GID: 01.0f.08.ae.fc.42.76.e3.01.00.00.00.00.00.12.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RELIABLE
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite

Subscription count: 1

Node name: _NODE_NAME_UNKNOWN_
Node namespace: _NODE_NAMESPACE_UNKNOWN_
Topic type: std_msgs/msg/String
Endpoint type: SUBSCRIPTION
GID: 62.d9.27.c1.f4.5d.2b.b8.0c.e8.0d.34.00.00.01.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: BEST_EFFORT
  History (Depth): UNKNOWN
  Durability: VOLATILE
  Lifespan: Infinite
  Deadline: Infinite
  Liveliness: AUTOMATIC
  Liveliness lease duration: Infinite
```

https://github.com/foxglove/studio/issues/2871

2022-03-20 11:43 UTC, wep21 commented
cc @jhurliman @jtbandes

2022-03-20 14:49 UTC, defunctzombie commented
Volatile is not compatible with `transient local` tho. and Best effort is not compatible with `reliable`.

That's my reading of the compatibility tables. Do you interpret them differently?

2022-03-20 15:08 UTC, wep21 commented
@defunctzombie I'm sorry, but I think my description is misleading. I mean the combination of publisher and subscriber qos is always compatible if the qos of subscriber has `volatile` durabiltiy and `best effort` reliability. Does it make sense?

2022-03-20 22:38 UTC, defunctzombie commented
Yep - that does make sense 👍

2022-03-21 19:00 UTC, jhurliman requested changes
I think we need to implement `BestEffort` handling in @foxglove/rtps before switching this library to use it. I also have reservations that this is the best default. The example code shows how to observe advertised topics and subscribe using the best QoS profile given the publisher's QoS profile, so any topic can be subscribed to. Changing this default means subscriptions would use unreliable UDP by default, which might cause unexpected results when packets are dropped.

2022-03-30 17:00 UTC, jhurliman approved these changes

2022-03-30 17:00 UTC, merged